spring.application.name=SmartQueue

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true


spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always


springdoc.swagger-ui.url=/v3/api-docs

security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}
security.jwt.refresh.expiration-time=${SECURITY_JWT_REFRESH_EXPIRATION_TIME}


app.security.cookie-secure=${APP_COOKIE_SECURE:true}

# Kafka Configuration
app.kafka.topic.business-events=business-events
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.bootstrap-servers=localhost:29092
spring.kafka.producer.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=smartqueue-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.max-poll-records=100
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

